numbers = [15, 25, 10, 30, 20, 5]
total = sum(numbers)
smallest = min(numbers)
largest = max(numbers)
average = total / len(numbers)
numbers_of_elements = len(numbers)
print("Total:", total)
print("Smallest:", smallest)
print("Largest:", largest)
print("Average:", average)
print("Number of elements:", numbers_of_elements)